#+title: AI 辅助写代码实战
#+author: 赵光建
#+date: 2025-12-08
#+options: ^:nil

* 概述
满坑满谷的都再说 AI 写代码多么多么的厉害，程序员都要被淘汰了，
我一直对此不以为然，上手操练一下，改变了我对 AI 的不屑和排斥。

* AI 上手过程
周末的晚上，向身处泰国的 李伟 发出求助，让其帮忙演示一下怎么用 AI 写代码，
他是个天生的程序员，有着前卫的嗅觉和够转的脑力，这类事情找他准没错。
发出求助的几秒后，回复：go，来
连上 Zoom 开搞，完整演示了一下他是如何操练的。
看完演示，我惊到了，抛开代码本身需要保密的事情不说，
AI 可以做到如此程度的提高程序员的研发效率，这是又惊又怕。
这里用“研发”两个字，是因为 AI 干活，必须让它经历一边方案设计的过程，切忌不能直接搞代码。
周一一早，送完孩子和老婆上班，坐下来，打开电脑，操练一下：
**Web 平台查询性能的场景**
1. 安装好 Cursor
2. 设置好支持 corsor 命令呼出 Cursor
3. 安装 rust-analyzer 插件，因为工程是用 Rust 写的
4. New Agent，选 Plan，Models 选自动，提出问题：
   漏洞数据达到30万时，查询速度慢，请结合源码和文档，给出解决方案
5. AI 哗啦哗啦一顿分析，输出了优化文档，包含了很多优化项目
6. 其中提到增加 tbl_vuln 表字段 last_modified_at 的索引，可以提高10倍速度，准备
   采纳这条优化建议
   怕 AI 会瞎搞我的代码，所以我手工创建了一个修改库表的 rs 文件
   sea-orm-cli migrate generate alter_tbl_vuln
   生成了文件 migration/src/m20251208_014825_alter_tbl_vuln.rs
7. 将模式选为 Agent，给出指令：
   请在 migration/src/m20251208_014825_alter_tbl_vuln.rs 文件中
   增加表 tbl_vuln 字段 last_modified_at 索引，提高查询的排序速度
8. 这时，Agent 开始哗啦哗啦干活，问我是否可以上网查询，允许，它开始查询 sea-orm 的
   官网文档，然后开始修改 rs 文件
   改后的文件，让我手工操作是否允许其中的修改，它改的真的没有问题，同意它的修改
   只添加了 if_not_exists()，其余完全正确
9. 编译成功
   本地环境，增加索引前 600ms，增加后 60ms
   生产环境，增加索引前 800ms，增加后 80ms

AI 辅助我完成了查询性能的优化，我没有输出任何优化思路的前提下，AI 给出了优化思路，
我判断并选择某一思路，AI 动手改代码，我审查代码，测试后，效果达到了预期。
整个过程非常和谐。
